export const SHIPPING_VALUES = {
    FREE_SHIPPING_VALUE: 400,
    FIXED_SHIPPING_VALUE: 30,
    MAX_KG_FOR_FIXED_SHIPPING_VALUE: 10,
    VALUE_FOR_EACH_KG_AFTER_MAX_FIXED_SHIPPING: 7/5 // 7 dollars for each 5 kg
};
